// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/generic/ActionCard.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    GameSessionManager: typeof import('./src/components/GameSessionManager.vue')['default']
    HeaderNavbar: typeof import('./src/components/layout/HeaderNavbar.vue')['default']
    PlayerList: typeof import('./src/components/features/player/PlayerList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/layout/ToggleTheme.vue')['default']
    WaitingRoom: typeof import('./src/components/WaitingRoom.vue')['default']
  }
}

export {}
