// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/generic/ActionCard.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    GameSessionManager: typeof import('./src/components/GameSessionManager.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HeaderNavbar: typeof import('./src/components/layout/HeaderNavbar.vue')['default']
    IcBaselineDarkMode: typeof import('~icons/ic/baseline-dark-mode')['default']
    'Mdi:sword': typeof import('~icons/mdi/sword')['default']
    'Mdi:user': typeof import('~icons/mdi/user')['default']
    'Mdi:users': typeof import('~icons/mdi/users')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    PlayerList: typeof import('./src/components/features/player/PlayerList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/layout/ToggleTheme.vue')['default']
    WaitingRoom: typeof import('./src/components/WaitingRoom.vue')['default']
  }
}

export {}
